site: plyr0
title: plyr0
greetings: elo!
description: >-
  my personal blog
  with random stuff
lang: en-US
timezone:  Europe/Warsaw
repo: # https://github.com/plyr0/plyr0.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: plyr0
  avatar: avatar.jpg
  url: "https://github.com/plyr0"
  email: your-email@email.com # email adress
  bio: just a minimalist, personal blog
  username: plyr0
  github: plyr0
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: your-email@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://plyr0.codeberg.page" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl:

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


